<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Customer;
use AppBundle\Repository\ICustomerRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository implements ICustomerRepository
{
    /**
     * @var EntityRepository
     */
    private $repository;
    
    /**
     * 
     * @var EntityManagerInterface
     */
    private $em;
   
    public function __construct(EntityManagerInterface $entityManager) {
        $this->repository = $entityManager->getRepository(Customer::class);
        $this->em = $entityManager;
    }
    
    public function findAll() {
        return $this->repository->findAll();
    }
    
    public function save(Customer $customer) {
        try {
            
            $this->em->persist($customer);
            $this->em->flush();
            return true;
        } catch (Exception $exc) {
            echo $exc->getTraceAsString();
            return false;
        }
    }
    
    public function delete(Customer $customer) {
        try {
            
            $this->em->remove($customer);
            $this->em->flush();
            return true;
        } catch (Exception $exc) {
            echo $exc->getTraceAsString();
            return false;
        }
    }
}
